/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package pl.futurecollars.invoicing;

public class App {

  public String getGreeting() {
    return "Sorting Stuff Out";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
  }
}
